# Generated by Django 4.1.6 on 2023-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0002_runway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_destination', to='airports.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_origin', to='airports.airport')),
            ],
        ),
    ]
