# Generated by Django 4.1.6 on 2023-03-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
