# Generated by Django 4.1.6 on 2023-03-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_number', models.IntegerField()),
                ('runway_designation', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('N', 'None')], default='N', max_length=1)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.airport')),
            ],
        ),
    ]
